# Generated by Django 6.0 on 2025-12-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.TextField(default='untitled'),
        ),
        migrations.AddField(
            model_name='todo',
            name='to_completed',
            field=models.BooleanField(default=False),
        ),
    ]
