# Generated by Django 6.0 on 2025-12-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_todo_date_todo_title_todo_to_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
