# Generated by Django 6.0 on 2025-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('saths', models.IntegerField()),
                ('sciene', models.IntegerField()),
                ('social_science', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('result', models.BooleanField()),
            ],
        ),
    ]
