# Generated by Django 6.0 on 2025-12-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_ranklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranklist',
            old_name='saths',
            new_name='maths',
        ),
    ]
