# Generated by Django 6.0 on 2025-12-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_saths_ranklist_maths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranklist',
            old_name='sciene',
            new_name='science',
        ),
    ]
